[tools]
python = "3.13.7"
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }
_.file = ".env"

[tasks.deps]
description = "Install Python dependencies with uv"
run = "uv sync"

[tasks.add]
description = "Add a new dependency (usage: mise add <package>)"
run = "uv add ${1:-}"

[tasks.add-dev]
description = "Add a new dev dependency (usage: mise add-dev <package>)"
run = "uv add --dev ${1:-}"

[tasks.test]
description = "Run pytest tests"
run = "pytest -vv tests/"

[tasks.format]
description = "Format code with ruff"
run = "ruff format ."

[tasks.lint]
description = "Lint and fix code with ruff"
run = "ruff check . --fix"

[tasks.typecheck]
description = "Type check with mypy"
run = "mypy ./src"

[tasks.migrate_db]
description = "Run database migrations"
run = "PYTHONPATH=src python -m journal.repository.migrate_db"

[tasks.run]
description = "Migrate DB and start uvicorn server"
run = [
    "PYTHONPATH=src python -m journal.repository.migrate_db",
    "PYTHONPATH=src uvicorn journal.main:prod_app --reload --factory"
]

[tasks.fix]
description = "Format and lint code"
depends = ["format", "lint"]
